#!/usr/bin/env bash

PROFILE=${1:-singularity}
echo "Using profile ${PROFILE}."

nextflow run main.nf \
    -profile ${PROFILE} \
    --library test_data/library.txt \
    --barcodes test_data/barcodes.txt \
    --inputDir test_data/01_raw \
    --outputDir test_output

OBSERVED='test_output/counts/library/counts_mageck.txt'
EXPECTED='test_data/expected_output.txt'
cmp --silent ${EXPECTED} ${OBSERVED} && \
    echo '--> SUCCESS: Expected Results!' || echo '--> FAILED: Inconsistent Results!'
