#!/usr/bin/env bash

PROFILE=${1:-ii2}
echo "Using profile ${PROFILE}."

nextflow run main.nf \
    -profile ${PROFILE} \
    --library test_data/library.txt \
    --barcodes test_data/barcodes.txt \
    --inputDir test_data/01_raw \
    --outputDir test_output
